### ISSUE TITLE
Framed pictures are translucent

### ISSUE THREAD

**Issue by inhumanesmoke** [Parallellines0451/GTAIV.EFLC.FusionShaders#1]
There seems to be an issue with glass framed pictures.  The image is translucent and you can see the wall behind it.  I found this at The Triangle  Club in Bohan.

**Comment by Parallellines0451** [comment]
That's probably a broken model which doesn't play nice with the restored stippled transparency. There are lots of them around the map, but Attramet will look into fixing them in his [Various Fixes](https://gtaforums.com/topic/975211-various-fixes/) mod.
