### ISSUE TITLE
Definition stays off

### ISSUE THREAD

**Issue by Assduster** [Parallellines0451/GTAIV.EFLC.FusionShaders#10]
Definition in the distance is deactivated always, just wish you could toggle it as well as motion blur and DoF. Can remove it completely when using the original rage_postfx file. Trying my best to explain the problem but what i essentially mean is that its blurry in the distance when using the rage_postfx included here whatever settings i toggle on or off

Love your work!

**Comment by Parallellines0451** [comment]
Toggle it in the in-game menu with FusionFix.
Or look for "if_eq c222.y, c222.w" and change the c222.y to c222.w and rebuild the shaders.
