### ISSUE TITLE
Lightning renders only in close proximity V200

### ISSUE THREAD

**Issue by Anargy** [Parallellines0451/GTAIV.EFLC.FusionShaders#13]
Lightning renders only in close proximity. GTA IV CE version 1.8.0, FusionFix installed and ASILoader included by FusionFix. 

Video
https://www.youtube.com/watch?v=sHCBwvVQ9PY

**Comment by Parallellines0451** [comment]
You didn't install FusionFix correctly. It's required to disable depth bounds test, which fixes that issue.
