### ISSUE TITLE
[Feature Request] Reflections on buildings, improvements in future?

### ISSUE THREAD

**Issue by r3538987** [Parallellines0451/GTAIV.EFLC.FusionShaders#15]
https://webmshare.com/play/KbLYA
On certain building you may see big reflections, I guess these are so called cubemaps, and these sometimes behaves oddly because positioning are affected by player camera position and angles. 
In result driving or moving past such constructions will catch your eye, because something is off there. 

Are there any ideas or plans to tackle these as well? 
Probably this is quite complicated topic and shaders wont help much.

**Comment by ghost** [comment]
Possibly related to cubemaps not being parallax-corrected?

Relevant SIGGRAPH presentation here: https://seblagarde.files.wordpress.com/2012/08/parallax_corrected_cubemap-siggraph2012.pdf
