### ISSUE TITLE
[Feature Request] Add a volumetric lighting quality / density toggle

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#16]
Volumetric lighting is normally tied to night shadows. Could a separate toggle that also controls its density properly be implemented?
This feature is very underutilized so making it cast from more light sources would be a nice improvement.

**Comment by Parallellines0451** [comment]
What determines whether volumetric lighting is used or not is simply the light models themselves. They need to have both the "cast rays" and the "cast shadows" flags enabled in order to display the effect.
