### ISSUE TITLE
[Request] Fix the player reflection

### ISSUE THREAD

**Issue by vavrinko** [Parallellines0451/GTAIV.EFLC.FusionShaders#20]
I have noticed that sometimes the player gets all shiny, as if wet, when it is not raining. Happens during cutscenes and during gameplay. Happens to NPCs as well. It is random as far as I can tell. Looks very out of place.

![r72PLZ9](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/96373757/2588fd7f-1b53-499e-9eb8-92b00a180819)
![05ZjR0r](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/96373757/25dd4f95-7261-4298-9bf4-bc138f126faf)

I am using Fusion Fix, which as I understand uses shader fixes collection.

Please help!

**Comment by Parallellines0451** [comment]
Not a bug, that's how the game looks on consoles too. Also I don't recommend enabling definition in FusionFix for the time being.

**Comment by vavrinko** [comment]
That does not mean it isn't a bug or oversight. NPCs getting wet when there is no water would be considered an issue no matter the platform.
Well, if it can't be helped it can't.

**Comment by Parallellines0451** [comment]
It has nothing to do with shaders, it's just how the vanilla timecycle is set up.

**Comment by vavrinko** [comment]
Yeah. I understand. Sorry if I seemed rude. I am just really annoyed at this point by the answer: It's like that on the consoles.
I played the 360 version and it wasn't perfect too.
I love your mod. I really do. I especially love that I can see the rain now. But this thing just breaks it for me. I am trying to find someone who could fix it, or show me how to fix it. You wouldn't happen to know a modder who takes commissions, btw?

Once again. I am sorry for sounding agitated. Love your mod and I'd like to continue using it, but I'll have to fix this thing first XD
Thank you for the fixes. And for your answer.

**Comment by Parallellines0451** [comment]
No problem, it's just not something for this repository to handle. I'm not sure which timecycle setting is responsible for it but you could probably use this to figure it out https://github.com/akifle47/InGameTimecycEditor (press F9 to use it). While you're at it maybe create something new and cool with it.

**Comment by vavrinko** [comment]
Oooh. That's awesome. I'll definitely try it.
Thanks a lot. It's nice of you :)

**Comment by vavrinko** [comment]
I just wanna thank you one more time, friend. I did not know about this tool but it was what I needed the whole time.
What I did isn't perfect, since the reflection of cars and NPCs is connected, but I managed to tone it down to my suit me. Unfortunately it's nothing worth publishing.

So thank you for your mod and for the advice. :)
