### ISSUE TITLE
[Issue] Depth Of Field Effects don't pass through transparency

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#22]
As mentioned here: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/141 Depth Of Field does not pass through transparent objects / materials.
Is this issue tied to the depth buffer the game was missing before? Could it be fixed now that we have a working one without breaking other things?
![GTAIV 10_18_2023 20_51_10](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/143945383/d7e6c93c-e032-4c99-ab48-d4fa27c03ee8)

**Comment by Parallellines0451** [comment]
This is something that would need to be handled through code injection, not shaders. We're looking into it.

**Comment by RecklessGlue540** [comment]
Good luck with it! Thank you for your consideration!

**Comment by Parallellines0451** [comment]
Closing due to several new issues that arise after fixing this.

**Comment by RecklessGlue540** [comment]
> Closing due to several new issues that arise after fixing this.

Oh..
I'm kind of curious. What are those? Sorry for asking too many questions but it seems interesting..

**Comment by Parallellines0451** [comment]
Mainly wrong render order in mirrors and no fog applied to distant building lights.
