### ISSUE TITLE
[Issue] Smoke / Particle Effects may randomly flicker depending on the camera angle sometimes

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#23]
Not asking for a fix, since I know camera angle dependant effects (Like the water foam) are very hard to fix, but i think it's worth pointing it out. Here is some footage:
https://streamable.com/46nz4t
It does not happen everytime though. I have no idea what may trigger it (probably Night Shadows as it stabilized after turning it off)
Seems to always trigger in TLAD's Intro. When taking Billy home. All those rain splashes will flicker...

**Comment by Parallellines0451** [comment]
Looks like an engine/CPU code issue so I'll close this.
