### ISSUE TITLE
[BUG] Cutscene Phone cord transparent with latest patch

### ISSUE THREAD

**Issue by vavrinko** [Parallellines0451/GTAIV.EFLC.FusionShaders#24]
Hello there. o/
I have noticed that the phone cord is transparent in the cutscene for the mission "Jamaican Heat". Haven't played much yet, maybe it is somewhere else too. It is definitely cause by the Fusion shaders, because when I delete the folder from the update folder it goes back to normal. Can you fix it please?

With Fusion 2.0
![280551609-2cf9a711-beca-4601-a362-bad2babe7832](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/96373757/996e74a2-a1fb-401a-bb7d-f3580e38238c)

With Fusion 2.0 - without shaders
![20231106130935_1](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/96373757/362dc742-4dd8-476e-9a1f-c11b13b8fdf4)

The models in question are
cs_cord.wdr
cs_cordclear.wdr
in pc/anim/cutprops.img

I haven't checked cs_cordred.wdr yet

(I've also posted this on the Fusion Fix Github, but since I learned that it is shader related I thought I put it directly here. Sorry for spamming.)

**Comment by Parallellines0451** [comment]
It's caused by a bad asset, the texture has an alpha channel. Thanks for the heads up though, I relayed this to the Various Fixes team.

**Comment by vavrinko** [comment]
nice. Thank You.
