### ISSUE TITLE
[Question | Possible Issue] Sun shadows are kinda fake?

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#25]
As mentioned here: https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1072218744
Sun shadows do not fall properly on surfaces. Some possible theories are found below that comment.
Now, could this be changed? As it's pretty obvious they're faked... even if it's intended...

**Comment by akifle47** [comment]
its to reduce shadow acne and probably make sunsets and sunrises brighter
its honestly really not that obvious they're "faked" but yes it can be changed with a 1 byte patch
![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/140577348/c9127bff-aac8-4dc2-a2b5-19debfe08e97) 
![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/140577348/97c2e39c-666b-45c7-8027-978033ed126e)

**Comment by Parallellines0451** [comment]
Yeah that's intended and most games do this to prevent depth bias and culling issues, so I'll close this.
