### ISSUE TITLE
Was this ever a thing in gta4?

### ISSUE THREAD

**Issue by vavrinko** [Parallellines0451/GTAIV.EFLC.FusionShaders#26]
![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/96373757/72f4a6c3-b803-4759-8515-426598c68569)

I was wondering about this feature. When it rained in old GTAs, the asphalt reflected headlights, lamps, traffic lights etc. I don't remember seeing it on xbox version of IV. Was it ever there? Is it something connected to shaders?

**Comment by RecklessGlue540** [comment]
> Was it ever there?

Pedestrians and vehicles reflecting on the ground (Or any other surface apart from mirrors and water) were never there in IV. 

> Is it something connected to shaders?

Maybe. Max Payne 3 has this, at least for the player (and it's also present on consoles there, along with the PC version on D3D9... Could be possible to do it, but 100% not in scope for FusionFix or Shader Fixes to handle this...
Maybe here? https://github.com/robi29/GTA-IV-Shaders

**Comment by vavrinko** [comment]
> > Was it ever there?
> 
> Pedestrians and vehicles reflecting on the ground (Or any other surface apart from mirrors and water) were never there in IV.
> 
> > Is it something connected to shaders?
> 
> Maybe. Max Payne 3 has this, at least for the player (and it's also present on consoles there, along with the PC version on D3D9... Could be possible to do it, but 100% not in scope for FusionFix or Shader Fixes to handle this... Maybe here? https://github.com/robi29/GTA-IV-Shaders

thanks :)
