### ISSUE TITLE
Config menu options all linked and changing at once...

### ISSUE THREAD

**Issue by mattha34** [Parallellines0451/GTAIV.EFLC.FusionShaders#27]
hi - whenever I go to change an option - the config option for all new options changes in sync, for example I change framerate - and the value for all other options is now set to 75 - even when it's a on/off type option. screenshots probably show better than I am explaining! 

![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/36822930/4a1752b6-adfc-4558-be17-2ec519e0030f)
![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/36822930/775c2e29-0ca2-4c5e-a209-3f2da9dc0321)
![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/36822930/c975ae6c-1189-466a-9e47-ec22c13661ef)

**Comment by Parallellines0451** [comment]
It looks like you installed FusionFix incorrectly. Make sure you're using the latest version of it, preferably on the latest version of the game.

**Comment by mattha34** [comment]
hey my bad I totally logged this on the wrong repo! I have latest version
so I'll head over there and log an issue!
