### ISSUE TITLE
[Feature Request] Reflections of trees on vehicles and dynamic shadows

### ISSUE THREAD

**Issue by Otheucarvalho** [Parallellines0451/GTAIV.EFLC.FusionShaders#30]
Would it be possible to add some reflections that are still missing in cars, like those of trees for example? I saw this only in Zolika1351's patch but unfortunately the version that has these features and the feature of some dynamic shadows that are still missing are not compatible with the CE version... 

Sorry my english

**Comment by Parallellines0451** [comment]
Not through shaders, those objects are blacklisted from reflection maps by CPU code.

Most shadow casting lights on PC are extremely broken and adding more through that mod just makes things worse, in fact I recommend using the console light models from here to fix several issues and improve performance https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/
