### ISSUE TITLE
[Feature Request] improved reflections in cars

### ISSUE THREAD

**Issue by Otheucarvalho** [Parallellines0451/GTAIV.EFLC.FusionShaders#32]
Option to make reflections reflect all map objects at full quality (including objects such as trees, lampposts, etc.)

To date I have only found one mod that does this, but unfortunately it has to be downgraded and it is not compatible with fusionfix, I hope one day to see this feature in updated versions of the game.

I understand a little about programming but it is very difficult to find any information to base myself on and try to make these changes. I admire the work you do!

**Comment by RecklessGlue540** [comment]
https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/30

I think you should move this to FusionFix. You already got an answer here. And besides, FusionFix takes care of the coding part.
Tho I doubt it will be a thing. Optimization is already bad. Straining it any further will completely mess up the game.
