### ISSUE TITLE
[Feature Resquest] Bokeh depth of field

### ISSUE THREAD

**Issue by DropsMJay** [Parallellines0451/GTAIV.EFLC.FusionShaders#35]
It is possible to replace the game's depth of field with a "Bokeh" one?

Thank you and keep up the good work.

**Comment by RecklessGlue540** [comment]
> It is possible to replace the game's depth of field with a "Bokeh" one?
> 
> Thank you and keep up the good work.

Scroll a bit through this: https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/blob/main/win32_30_nv8/rage_postfx/rage_postfxPS12.asm
It already is Bokeh DOF.
