### ISSUE TITLE
motion blur

### ISSUE THREAD

**Issue by fenderjaguarnet** [Parallellines0451/GTAIV.EFLC.FusionShaders#37]
please can you just make it so that the motion blur just works all the time in the car, rather than only kicking in at a fast speed? 

the "Ultimate Graphic Tweak" one was the best, although I don't think it's compatible with the lastest patch of the game

**Comment by Parallellines0451** [comment]
Not possible through shaders. Might be possible by editing visualsettings.dat, but I can't confirm.
