### ISSUE TITLE
[Bug] Weird line in the water in some places

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#39]
https://streamable.com/98obdk

I have noticed this in Middle Park and other places too, wonder what's wrong... Hopefully it ain't another CPU code issue 😄

**Comment by Parallellines0451** [comment]
[Fixed](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/commit/4fe4b3ea1a6d0d9c5608573ef555965ed65b3096)
