### ISSUE TITLE
Possible fix for lamppost double shadows / paraboloid distortion?

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#40]
I think I found some interesting articles that might help with fixing the paraboloid distortions Night Shadows are plagued with, without the need of tessellation, by shifting some of the vertex shader's work to the pixel shader, though something like that may also require code so I don't know if it's in plans...

http://www.gamedevelop.eu/en/tutorials/dual-paraboloid-shadow-mapping.htm
http://www.klayge.org/material/3_12/DPSM/DPSM.PDF

![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/143945383/a7a0a7af-bdef-497d-94ca-6e500c4d0d85)

![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/143945383/b36880a6-b16d-4e40-9bdb-9c815bd02ade)

Reading the second one actually seems to be making a little bit of sense tbh...

**Comment by Parallellines0451** [comment]
Can't be viably done through shaders only. CPU code editing is needed.
Besides, technically these shadows weren't meant to be used everywhere. PC lamppost shadowcasting is not intended behavior by the original developers. Just use console lampposts.
