### ISSUE TITLE
V220 Pre-Release car paint looks uneven

### ISSUE THREAD

**Issue by TiberiusMars** [Parallellines0451/GTAIV.EFLC.FusionShaders#42]
I'm using FusionFix, DXVK, and Various Fixes (no Console Visuals).
Everything works great, but the car surfaces look uneven. I've tracked down the issue to these:

gta_vehicle_paint1.fxc
gta_vehicle_paint2.fxc
gta_vehicle_paint3.fxc

Replacing those with the ones from v210 fixes the issue.

**Comment by Parallellines0451** [comment]
Uneven? Can you provide any screenshots? What version of FusionFix are you using?

**Comment by TiberiusMars** [comment]
I am using 2.5.6.
![V210](https://github.com/user-attachments/assets/ac0eda27-622f-4823-b19c-2b2459b4cfb7)
![V220](https://github.com/user-attachments/assets/4024a2fd-5107-47e5-ba3f-6c71528d0cee)
I also just noticed that the shadow softness setting doesn't do anything with v220, maybe it's something else or just me.

**Comment by RecklessGlue540** [comment]
Do not use the new shaders with the old FusionFix. They are not compatible. Wait for the next FusionFix release, or preview it using this method but expect issues https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/28#issuecomment-2246274667

**Comment by Parallellines0451** [comment]
Those shaders are only meant to be used with the next version of FusionFix.
