### ISSUE TITLE
V220 Pre-Release shadow softness settings not working

### ISSUE THREAD

**Issue by TiberiusMars** [Parallellines0451/GTAIV.EFLC.FusionShaders#43]
I'm using FusionFix 2.5.6, DXVK, and Various Fixes (no Console Visuals).
None of the softness settings do anything (shadows remain sharp). I've tracked down the issue to this:

deferred_lighting.fxc

Replacing it with the one from v210 fixes the issue.

V220 deferred_lighting.fxc:
![V220_deferred_lighting](https://github.com/user-attachments/assets/d88686ad-2285-4ff2-8fa5-357ed9e3a20f)

V210 deferred_lighting.fxc:
![V210_deferred_lighting](https://github.com/user-attachments/assets/91cbbb9f-5dfe-4657-8ed0-68e6eb4c425f)

**Comment by Parallellines0451** [comment]
https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/42#issuecomment-2259198186
