### ISSUE TITLE
[Question] Bugged "Off" Reflections

### ISSUE THREAD

**Issue by RecklessGlue540** [Parallellines0451/GTAIV.EFLC.FusionShaders#44]
https://github.com/GTAmodding/GTAIV-Issues-List/issues/141

Just wondering, is this an issue in game code or shaders? I'd bet it is the former but I'm still kind of curious 😄 
And yeah it seems to occur with the latest preview FF as well so it wasn't fixed as a side effect of some change either lol

**Comment by Parallellines0451** [comment]
Off reflections or shadows aren't supported.
