### ISSUE TITLE
Circle Bloom Effect with smoothstep?

### ISSUE THREAD

**Issue by t-ro86** [Parallellines0451/GTAIV.EFLC.FusionShaders#47]
Will we see soon this kind of effect? Now the bloom effect is still with cross form and this makes the lights, light sources and reflected flares rough and ugly, it's can be disabled but without it the light sources are just a colors.

**Comment by Parallellines0451** [comment]
It's possible to make it circular like conventional bloom, but it's nearly impossible to make it look consistent and faithful to the original in terms of intensity.
