### ISSUE TITLE
[Question] Compiling pre-200 releases with enabled Xbox Gamma

### ISSUE THREAD

**Issue by ghost** [Parallellines0451/GTAIV.EFLC.FusionShaders#49]
Hi, I remember that when compiled releases of these were provided here, Xbox Gamma was enabled with a replacement rage-postfx.fxc (at least in 106). How can I enable it in the code?

**Comment by Parallellines0451** [comment]
If needed for whatever reason, you can take the small snippet of code from the bottom of rage_postfxPS12, 14, 24, 26 or 28. It's just a rough approximation, however.

And old versions are unsupported.

**Comment by ghost** [comment]
Well, and how can it be enabled?
