### ISSUE TITLE
How do I install these shaders?

### ISSUE THREAD

**Issue by LegzRwheelz** [Parallellines0451/GTAIV.EFLC.FusionShaders#51]
Hi, I seem to be missing something..I cannot figure out how to install these shaders. I can't find a write-up or install tut anywhere. Perhaps my google-fu is wack...IDK. I have FusionFIx installed and absolutely have no issues installing mods, I've even created a few Fusion compatible mods from older mods, so it isn't that I am a noob or dum-dum-dingleberry (ok I am a dingleberry😅), just that this one has left me scratching my head.

Any help is greatly appreciated, thanks in advance guys!

**Comment by Parallellines0451** [comment]
FusionFix compiles the shaders from here, they are already included in it.

**Comment by LegzRwheelz** [comment]
So just using fusion fix automatically compiles the shaders?
