### ISSUE TITLE
Intel CMAA2: A Better Post Processing Anti-Aliasing Solution

### ISSUE THREAD

**Issue by SuleMareVientu** [Parallellines0451/GTAIV.EFLC.FusionShaders#6]
It should be possible to use this implementation of Intel's CMAA to achieve better results then FXAA at the same performance cost.

Shader Model 3 (Reshade) Implementation: [https://github.com/Mortalitas/GShade/blob/master/Shaders/CMAA_2.fx](https://github.com/Mortalitas/GShade/blob/master/Shaders/CMAA_2.fx)

Intel Article regarding CMAA2 benefits over FXAA: [https://www.intel.com/content/www/us/en/developer/articles/technical/conservative-morphological-anti-aliasing-20.html](https://www.intel.com/content/www/us/en/developer/articles/technical/conservative-morphological-anti-aliasing-20.html)

Unfortunately I don't have the knowledge to write assembly nor the required experience with shaders to "convert" the reshade implementation to simple HLSL (which is supported by RAGE Shader Editor C++), but I taught it could be helpful to bring this to your attention. Close this issue if you find it inappropriate, thanks.

**Comment by Parallellines0451** [comment]
Unfortunately it wouldn't be possible or practical to implement CMAA2 or even SMAA natively. We're limited to a single post processing pass and FXAA is the only method that really fits the bill. Thanks for the feedback though.

**Comment by RecklessGlue540** [comment]
Since we now have native SMAA, would CMAA2 even be any better than it, since it'd probably be possible as of result now too?

Just asking as I wonder if AA can be made any better than it is currently...

**Comment by Parallellines0451** [comment]
Even FXAA is perfectly good for a simple game like IV, there's not much of a point in adding options just for the sake of it.
