### ISSUE TITLE
Helicopter ripple effect on water is missing with nv8 shader

### ISSUE THREAD

**Issue by sTc2201** [Parallellines0451/GTAIV.EFLC.FusionShaders#7]
This effect to be more precise.

![ripple](https://i.imgur.com/Kgtul1d.png)

The deferred_lighting.fxc shader in the nv8 folder is causing this, so this issue may occur with NVIDIA GPUs only since I'm using one.

I took the vanilla nv8 deferred_lighting.fxc and replaced the assembly files with the modified ones (vanilla files had no differences anyway) and this restored the effect + the fixes without any issues.

I guess nv8 needs to have a separate deferred_lighting.fxc to avoid this.

**Comment by Parallellines0451** [comment]
Fixed, it was caused by atidx10 shaders.
